[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "hubspot.crm.pipelines"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot", "crm", "pipelines"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.pipelines"

[build-options]
observabilityIncluded = true
